// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Astronomy.Data.EF.Models
{
    public partial class HabHyg
    {
        public int HabHygId { get; set; }
        public int Hip { get; set; }
        public byte? Hab { get; set; }
        public string DisplayName { get; set; }
        public int? Hyg { get; set; }
        public string BayerFlamsteed { get; set; }
        public string Gliese { get; set; }
        public string Bd { get; set; }
        public int? Hd { get; set; }
        public short? Hr { get; set; }
        public string ProperName { get; set; }
        public string SpectralClass { get; set; }
        public double Distance { get; set; }
        public double Xg { get; set; }
        public double Yg { get; set; }
        public double Zg { get; set; }
        public double AbsMag { get; set; }
    }
}