// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Astronomy.Data.EF.Models
{
    public partial class HygDatum
    {
        public int Id { get; set; }
        public int? HipparcosId { get; set; }
        public int? HenryDraperId { get; set; }
        public int? HarvardRevisedId { get; set; }
        public string ProperName { get; set; }
        public string BayerFlamsteed { get; set; }
        public string GlieseCatalogId { get; set; }
        public string SpectralType { get; set; }
        public double RightAscension { get; set; }
        public double Declination { get; set; }
        public double DistanceInParsecs { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public double Z { get; set; }
        public double Xg { get; set; }
        public double Yg { get; set; }
        public double Zg { get; set; }
        public double RightAscensionRadians { get; set; }
        public double DeclinationRadians { get; set; }
    }
}